<a href="https://colab.research.google.com/github/NidhishGore/Hospital-Project/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import warnings
warnings.filterwarnings('ignore')
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

In [2]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive',force_remount=True)

# Access the dataset in Google Drive
dataset_path = '/content/drive/My Drive/Project/Hospital_Inpatient_Discharges.csv'

Mounted at /content/drive

In [3]:
# Read the csv file into a Pandas DataFrame
df = pd.read_csv(dataset_path)

In [4]:
list(df.columns)

['Hospital Service Area',
 'Hospital County',
 'Operating Certificate Number',
 'Permanent Facility Id',
 'Facility Name',
 'Age Group',
 'Zip Code - 3 digits',
 'Gender',
 'Race',
 'Ethnicity',
 'Length of Stay',
 'Type of Admission',
 'Patient Disposition',
 'Discharge Year',
 'CCSR Diagnosis Code',
 'CCSR Diagnosis Description',
 'CCSR Procedure Code',
 'CCSR Procedure Description',
 'APR DRG Code',
 'APR DRG Description',
 'APR MDC Code',
 'APR MDC Description',
 'APR Severity of Illness Code',
 'APR Severity of Illness Description',
 'APR Risk of Mortality',
 'APR Medical Surgical Description',
 'Payment Typology 1',
 'Payment Typology 2',
 'Payment Typology 3',
 'Birth Weight',
 'Emergency Department Indicator',
 'Total Charges',
 'Total Costs']

In [5]:
df.shape

(2352807, 33)

In [6]:
pd.set_option('display.max_columns',500)

In [7]:
df

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,Length of Stay,Type of Admission,Patient Disposition,Discharge Year,CCSR Diagnosis Code,CCSR Diagnosis Description,CCSR Procedure Code,CCSR Procedure Description,APR DRG Code,APR DRG Description,APR MDC Code,APR MDC Description,APR Severity of Illness Code,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,Capital/Adirond,Columbia,1001000.0,146.0,Columbia Memorial Hospital,50 to 69,125,F,White,Not Span/Hispanic,2,Elective,Short-term Hospital,2018,CIR020,CEREBRAL INFARCTION,NaN,NaN,45.0,CVA & PRECEREBRAL OCCLUSION W INFARCT,1.0,DISEASES AND DISORDERS OF THE NERVOUS SYSTEM,3.0,Major,Major,Medical,"Managed Care, Unspecified",Self-Pay,NaN,NaN,True,"17,591.41","3,570.06"
1,New York City,Manhattan,7002009.0,1445.0,Harlem Hospital Center,50 to 69,100,F,Black/African American,Not Span/Hispanic,16,Emergency,Short-term Hospital,2018,RSP017,POSTPROCEDURAL OR POSTOPERATIVE RESPIRATORY SY...,ESA003,MECHANICAL VENTILATION,121.0,OTHER RESPIRATORY & CHEST PROCEDURES,4.0,DISEASES AND DISORDERS OF THE RESPIRATORY SYSTEM,4.0,Extreme,Extreme,Surgical,Medicare,Medicaid,NaN,NaN,True,"106,190.21","78,913.24"
2,New York City,Manhattan,7002009.0,1445.0,Harlem Hospital Center,50 to 69,100,F,Black/African American,Not Span/Hispanic,4,Emergency,Home or Self Care,2018,MBD003,BIPOLAR AND RELATED DISORDERS,MHT001,PHARMACOTHERAPY FOR MENTAL HEALTH (EXCLUDING S...,753.0,BIPOLAR DISORDERS,19.0,MENTAL DISEASES AND DISORDERS,2.0,Moderate,Minor,Medical,Medicaid,NaN,NaN,NaN,False,"5,600","4,161.53"
3,New York City,Kings,7001016.0,1301.0,Kings County Hospital Center,18 to 29,112,M,Black/African American,Not Span/Hispanic,2,Emergency,Home or Self Care,2018,CIR017,CARDIAC DYSRHYTHMIAS,IMG008,ULTRASONOGRAPHY,201.0,CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS,5.0,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM,2.0,Moderate,Minor,Medical,Medicaid,Medicaid,NaN,NaN,True,"15,965.54","11,341.3"
4,New York City,Manhattan,7002054.0,1464.0,New York-Presbyterian Hospital - Columbia Pres...,0 to 17,104,M,Multi-racial,Not Span/Hispanic,2,Emergency,Home or Self Care,2018,RSP002,PNEUMONIA (EXCEPT THAT CAUSED BY TUBERCULOSIS),NaN,NaN,139.0,OTHER PNEUMONIA,4.0,DISEASES AND DISORDERS OF THE RESPIRATORY SYSTEM,3.0,Major,Moderate,Medical,Medicaid,Medicaid,Self-Pay,NaN,True,"36,846.83","10,240.02"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2352802,New York City,Queens,7003001.0,1628.0,Flushing Hospital Medical Center,30 to 49,113,M,White,Not Span/Hispanic,2,Emergency,Left Against Medical Advice,2018,MBD018,OPIOID-RELATED DISORDERS,SUD001,SUBSTANCE USE DETOXIFICATION,770.0,"DRUG & ALCOHOL ABUSE OR DEPENDENCE, LEFT AGAIN...",20.0,ALCOHOL/DRUG USE AND ALCOHOL/DRUG INDUCED ORGA...,1.0,Minor,Minor,Medical,Medicaid,NaN,NaN,NaN,False,"6,764","1,722.84"
2352803,New York City,Kings,7001021.0,1306.0,New York - Presbyterian Brooklyn Methodist Hos...,70 or Older,112,M,Black/African American,Not Span/Hispanic,7,Emergency,Home or Self Care,2018,INF002,SEPTICEMIA,NaN,NaN,720.0,SEPTICEMIA & DISSEMINATED INFECTIONS,18.0,INFECTIOUS AND PARASITIC DISEASES (SYSTEMIC OR...,4.0,Extreme,Major,Medical,Medicare,Medicare,Self-Pay,NaN,True,"43,488.79","11,414.6"
2352804,New York City,Kings,7001021.0,1306.0,New York - Presbyterian Brooklyn Methodist Hos...,30 to 49,112,F,White,Spanish/Hispanic,11,Emergency,Home or Self Care,2018,GEN001,NEPHRITIS; NEPHROSIS; RENAL SCLEROSIS,URN002,KIDNEY AND OTHER URINARY TRACT BIOPSY (NON-END...,462.0,NEPHRITIS & NEPHROSIS,11.0,DISEASES AND DISORDERS OF THE KIDNEY AND URINA...,2.0,Moderate,Moderate,Medical,Medicaid,Self-Pay,NaN,NaN,True,"86,509.76","19,997.25"
2352805,New York City,Kings,7001021.0,1306.0,New York - Presbyterian Brooklyn Methodist Hos...,18 to 29,112,F,White,Not Span/Hispanic,2,Emergency,Home or Self Care,2018,PRG022,PROLONGED PREGNANCY,PGN002,SPONTANEOUS VAGINAL DELIVERY,560.0,VAGINAL DELIVERY,14.0,"PREGNANCY, CHILDBIRTH AND THE PUERPERIUM",1.0,Minor,Minor,Medical,Medicaid,Medicaid,Self-Pay,NaN,True,"21,954.93","11,657.6"
2352806,New York City,Kings,7001021.0,1306.0,New York - Presbyterian Brooklyn Methodist Hos...,70 or Older,112,M,Black/African American,Not Span/Hispanic,3,Emergency,Skilled Nursing Home,2018,END001,THYROID DISORDERS,ENP002,THYROIDECTOMY,404.0,"THYROID, PARATHYROID & THYROGLOSSAL PROCEDURES",10.0,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES ...",2.0,Moderate,Moderate,Surgical,Medicaid,Self-Pay,NaN,NaN,False,"58,141.34","24,068.99"

In [8]:
df.head()

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,Length of Stay,Type of Admission,Patient Disposition,Discharge Year,CCSR Diagnosis Code,CCSR Diagnosis Description,CCSR Procedure Code,CCSR Procedure Description,APR DRG Code,APR DRG Description,APR MDC Code,APR MDC Description,APR Severity of Illness Code,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,Capital/Adirond,Columbia,1001000.0,146.0,Columbia Memorial Hospital,50 to 69,125,F,White,Not Span/Hispanic,2,Elective,Short-term Hospital,2018,CIR020,CEREBRAL INFARCTION,NaN,NaN,45.0,CVA & PRECEREBRAL OCCLUSION W INFARCT,1.0,DISEASES AND DISORDERS OF THE NERVOUS SYSTEM,3.0,Major,Major,Medical,"Managed Care, Unspecified",Self-Pay,NaN,NaN,True,"17,591.41","3,570.06"
1,New York City,Manhattan,7002009.0,1445.0,Harlem Hospital Center,50 to 69,100,F,Black/African American,Not Span/Hispanic,16,Emergency,Short-term Hospital,2018,RSP017,POSTPROCEDURAL OR POSTOPERATIVE RESPIRATORY SY...,ESA003,MECHANICAL VENTILATION,121.0,OTHER RESPIRATORY & CHEST PROCEDURES,4.0,DISEASES AND DISORDERS OF THE RESPIRATORY SYSTEM,4.0,Extreme,Extreme,Surgical,Medicare,Medicaid,NaN,NaN,True,"106,190.21","78,913.24"
2,New York City,Manhattan,7002009.0,1445.0,Harlem Hospital Center,50 to 69,100,F,Black/African American,Not Span/Hispanic,4,Emergency,Home or Self Care,2018,MBD003,BIPOLAR AND RELATED DISORDERS,MHT001,PHARMACOTHERAPY FOR MENTAL HEALTH (EXCLUDING S...,753.0,BIPOLAR DISORDERS,19.0,MENTAL DISEASES AND DISORDERS,2.0,Moderate,Minor,Medical,Medicaid,NaN,NaN,NaN,False,"5,600","4,161.53"
3,New York City,Kings,7001016.0,1301.0,Kings County Hospital Center,18 to 29,112,M,Black/African American,Not Span/Hispanic,2,Emergency,Home or Self Care,2018,CIR017,CARDIAC DYSRHYTHMIAS,IMG008,ULTRASONOGRAPHY,201.0,CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS,5.0,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM,2.0,Moderate,Minor,Medical,Medicaid,Medicaid,NaN,NaN,True,"15,965.54","11,341.3"
4,New York City,Manhattan,7002054.0,1464.0,New York-Presbyterian Hospital - Columbia Pres...,0 to 17,104,M,Multi-racial,Not Span/Hispanic,2,Emergency,Home or Self Care,2018,RSP002,PNEUMONIA (EXCEPT THAT CAUSED BY TUBERCULOSIS),NaN,NaN,139.0,OTHER PNEUMONIA,4.0,DISEASES AND DISORDERS OF THE RESPIRATORY SYSTEM,3.0,Major,Moderate,Medical,Medicaid,Medicaid,Self-Pay,NaN,True,"36,846.83","10,240.02"

In [9]:
df.tail()

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,Length of Stay,Type of Admission,Patient Disposition,Discharge Year,CCSR Diagnosis Code,CCSR Diagnosis Description,CCSR Procedure Code,CCSR Procedure Description,APR DRG Code,APR DRG Description,APR MDC Code,APR MDC Description,APR Severity of Illness Code,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
2352802,New York City,Queens,7003001.0,1628.0,Flushing Hospital Medical Center,30 to 49,113,M,White,Not Span/Hispanic,2,Emergency,Left Against Medical Advice,2018,MBD018,OPIOID-RELATED DISORDERS,SUD001,SUBSTANCE USE DETOXIFICATION,770.0,"DRUG & ALCOHOL ABUSE OR DEPENDENCE, LEFT AGAIN...",20.0,ALCOHOL/DRUG USE AND ALCOHOL/DRUG INDUCED ORGA...,1.0,Minor,Minor,Medical,Medicaid,NaN,NaN,NaN,False,"6,764","1,722.84"
2352803,New York City,Kings,7001021.0,1306.0,New York - Presbyterian Brooklyn Methodist Hos...,70 or Older,112,M,Black/African American,Not Span/Hispanic,7,Emergency,Home or Self Care,2018,INF002,SEPTICEMIA,NaN,NaN,720.0,SEPTICEMIA & DISSEMINATED INFECTIONS,18.0,INFECTIOUS AND PARASITIC DISEASES (SYSTEMIC OR...,4.0,Extreme,Major,Medical,Medicare,Medicare,Self-Pay,NaN,True,"43,488.79","11,414.6"
2352804,New York City,Kings,7001021.0,1306.0,New York - Presbyterian Brooklyn Methodist Hos...,30 to 49,112,F,White,Spanish/Hispanic,11,Emergency,Home or Self Care,2018,GEN001,NEPHRITIS; NEPHROSIS; RENAL SCLEROSIS,URN002,KIDNEY AND OTHER URINARY TRACT BIOPSY (NON-END...,462.0,NEPHRITIS & NEPHROSIS,11.0,DISEASES AND DISORDERS OF THE KIDNEY AND URINA...,2.0,Moderate,Moderate,Medical,Medicaid,Self-Pay,NaN,NaN,True,"86,509.76","19,997.25"
2352805,New York City,Kings,7001021.0,1306.0,New York - Presbyterian Brooklyn Methodist Hos...,18 to 29,112,F,White,Not Span/Hispanic,2,Emergency,Home or Self Care,2018,PRG022,PROLONGED PREGNANCY,PGN002,SPONTANEOUS VAGINAL DELIVERY,560.0,VAGINAL DELIVERY,14.0,"PREGNANCY, CHILDBIRTH AND THE PUERPERIUM",1.0,Minor,Minor,Medical,Medicaid,Medicaid,Self-Pay,NaN,True,"21,954.93","11,657.6"
2352806,New York City,Kings,7001021.0,1306.0,New York - Presbyterian Brooklyn Methodist Hos...,70 or Older,112,M,Black/African American,Not Span/Hispanic,3,Emergency,Skilled Nursing Home,2018,END001,THYROID DISORDERS,ENP002,THYROIDECTOMY,404.0,"THYROID, PARATHYROID & THYROGLOSSAL PROCEDURES",10.0,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES ...",2.0,Moderate,Moderate,Surgical,Medicaid,Self-Pay,NaN,NaN,False,"58,141.34","24,068.99"

In [10]:
(df.isnull().sum() / len(df)) * 100

Hospital Service Area                   0.380312
Hospital County                         0.380312
Operating Certificate Number            0.380312
Permanent Facility Id                   0.374191
Facility Name                           0.000000
Age Group                               0.000000
Zip Code - 3 digits                     1.788970
Gender                                  0.000000
Race                                    0.000000
Ethnicity                               0.000000
Length of Stay                          0.000000
Type of Admission                       0.000000
Patient Disposition                     0.000000
Discharge Year                          0.000000
CCSR Diagnosis Code                     0.002508
CCSR Diagnosis Description              0.002508
CCSR Procedure Code                    30.489114
CCSR Procedure Description             30.489114
APR DRG Code                            0.000128
APR DRG Description                     0.000128
APR MDC Code                            0.000128
APR MDC Description                     0.000128
APR Severity of Illness Code            0.000128
APR Severity of Illness Description     0.006715
APR Risk of Mortality                   0.006715
APR Medical Surgical Description        0.000000
Payment Typology 1                      0.000000
Payment Typology 2                     39.002859
Payment Typology 3                     78.727197
Birth Weight                           90.527400
Emergency Department Indicator          0.000000
Total Charges                           0.000000
Total Costs                             0.000000
dtype: float64